---
- question: "One advantage to making a project open source from the start is:"
  answer: 1
  choices:
    - You don't get as much scrutiny from management.
    - You can start getting feedback from lots of people right from the start.
    - You don't have licensing problems.
- question: "When starting a new project, it's important to:"
  answer: 1
  choices:
    - Keep the project under wraps until it's finished.
    - Concentrate on the right tools as much as on writing the code.
    - Keep the number of people involved small.
