cache:
  directories:
    - vendor/bundle
    - build
deploy:
  - provider: s3
    access_key_id: 'abcd'
    secret_access_key: 'efgh'
    bucket: learn-preprod.getchef.com
    skip_cleanup: true
    local-dir: build
    on:
      branch: master
install: bundle install --deployment --without development
script: bundle exec middleman build
