before_install: ./bin/preinstall-travis-deploy-dependencies
bundler_args: --deployment --without development
cache:
  bundler: true
  directories:
    - $(rvm gemdir)
    - build
deploy:
  # Prod
  - provider: s3
    access_key_id: # chef-prod learn-chef IAM user
      secure: "EQIbgGOlxHtkExVO/9kuMiZk65kyKfO/gBu/cvlISeMBtsN5/GmS3cKzcLeHU4LVqyViAIxzrJ88Ph2WrWUBrQhREhveJBkfzgTUZ2guGiKZS5W5rUpiaQ9Q/rstuEc1xyw+2EUrcNcskFMthYaXTCZ8mZjn150HCl4zyREEMVQ="
    secret_access_key:
      secure: "pmZTPeOJXFyxiRwK0CrQX6/iY9whTUIpurADleJ3Vnp7gRuLDbIwIWGKOg+UEh/aY3hMfakKo1+tkkmrT02g/6iGYdRUL54BiIrFubyF/1HU3xD4zrDV/KIsH604k0PQJRq7P1HwQ1iVyzgJIEl3e56lDe8fTi52RMyCvP5oi/c="
    bucket: learn.getchef.com
    endpoint: learn.getchef.com.s3-website-us-east-1.amazonaws.com
    skip_cleanup: true
    local-dir: build
    on:
      branch: release
    after_deploy: bundle exec middleman invalidate
  # Preprod
  - provider: s3
    access_key_id: # chef-preprod learn-chef IAM user
      secure: "qKNaFrRrVJAxflH56cZhy4bsZ7Hm5IYql3++ko7LlPa5yMCbfBS+9A4McXEv+0axlT6ytzSUfEkl7KKZLY4VX4RjF/GM95HTA5gAc8Ko6unAyfv1K2pQDTYtoNR4XVSGtBcwNREkXlTY52e3PEM31pwa9n1yKOnDqaPG5s+e4wg="
    secret_access_key:
      secure: "C5tFJ82XCansErEWXlgdFAJbGi3Q8Yd08xSa+UtJlQ6JcnhJsWic9o90bvJJLzygm2oy2KpXAB1ma2ygOL02mZqvOqF1tznPwIG10StMsMGkj+C4sCoSMnMm5Hg1Rh0HL4t5OVGMVj3COeYisX1agWV+xo0mx8X1O2j4Db6Gy/U="
    bucket: learn-preprod.getchef.com
    skip_cleanup: true
    local-dir: build
    on:
      branch: master
  # Sandbox
  - provider: s3
    access_key_id: # chef-preprod learn-chef IAM user
      secure: "qKNaFrRrVJAxflH56cZhy4bsZ7Hm5IYql3++ko7LlPa5yMCbfBS+9A4McXEv+0axlT6ytzSUfEkl7KKZLY4VX4RjF/GM95HTA5gAc8Ko6unAyfv1K2pQDTYtoNR4XVSGtBcwNREkXlTY52e3PEM31pwa9n1yKOnDqaPG5s+e4wg="
    secret_access_key:
      secure: "C5tFJ82XCansErEWXlgdFAJbGi3Q8Yd08xSa+UtJlQ6JcnhJsWic9o90bvJJLzygm2oy2KpXAB1ma2ygOL02mZqvOqF1tznPwIG10StMsMGkj+C4sCoSMnMm5Hg1Rh0HL4t5OVGMVj3COeYisX1agWV+xo0mx8X1O2j4Db6Gy/U="
    bucket: learn-sandbox.getchef.com
    skip_cleanup: true
    local-dir: build
    on:
      branch: sandbox
env:
  global:
    - CLOUDFRONT_DISTRIBUTION_ID=E1WC83ND9PN8RY
    # PREPROD_AWS_ACCESS_KEY_ID
    - secure: "mA2cVclqelvN22KD28gYMaMtIbukBgcS9fjXHYBfQLHnhNw/L/JrupAaBdE0mSosEITsHQua4Sxe00HsPB49UYrYX6zC8Q4FJa/LYmcz+XjdIK7kal3ZWUKu8HqCnqLncAm35hsWsaek0LsZRAKWYEJxTXOnKZKR266k7m1x5G8="
    # PREPROD_AWS_SECRET_ACCESS_KEY
    - secure: "cd0WPcv+jCzvOZgwNNcdO+vFVSuvoWwiq4iKPmwy8f2YerQ5Lv0DLshQeGLkTnRrLQK9xkGxyJQutOp35dhpc4kXR1suUFD7GdefAv0fd0mVMHthe/Hts/63XrwQgRN0hQMVPY0OInUcFm9FSWKQq9E2H0QnwKhggLZh0+H0yro="
    - PREPROD_AWS_S3_BUCKET=learn-preprod.getchef.com
    # PROD_AWS_ACCESS_KEY_ID
    - secure: "Uj+cLgQNwo+IlWGEwYFN+Sk8zIV9z8ltERf31h1Lv1PJq9eEVHHJxjBoqVSkd7NapKs+jeF9upSxJ0asstI/5Ph8Gdz6IvXA6u1VKxXHRcKWNLEyd6vvCUJmLJcMeH3MOWRKGszTYBaNyQaW5eO9qoBJCXcviVg82Ts9AuH0fS4="
    # PROD_AWS_SECRET_ACCESS_KEY
    - secure: "HKr7eZEgzAcfE/ykJn4aWQNWvbM+iHRqYCEhUFQa7PjiDLBk09qjT5umieSu9889WvJcYpaj6rTtKFeFYfgy50NGHCIN29Ca1a1wir2Xabpu9lo8kAR9YmVFuuYl6/ezB5YS5aCUejAAi6suUKRdXYhE7vX94rsotA2lh/42uY0="
    - PROD_AWS_S3_BUCKET=learn.getchef.com
    - SANDBOX_AWS_S3_BUCKET=learn-sandbox.getchef.com
script: bundle exec middleman build
