deploy:
  - provider: s3
    access_key_id: 'abcd'
    secret_access_key: 'efgh'
    bucket: preprod.learnchef.com
    skip_cleanup: true
    local-dir: build
    on:
      all_branches: true
install: bundle install --deployment --without development
script: bundle exec middleman build
