---
driver:
  name: azurerm

driver_config:
  subscription_id: 12345678-YOUR-GUID-HERE-123456789ABC
  location: "East US"
  machine_size: "Standard_D1"

transport:
  ssh_key: /root/.ssh/learn-chef.pem

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
    driver_config:
      image_urn: Canonical:UbuntuServer:14.04.5-LTS:14.04.201703070
      vm_name: ubuntu-vm
      vm_tags:
        ostype: linux
        distro: ubuntu

suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
