---
- question: What is a _node object_?
  answer: 1
  choices:
    - Any system that is managed by Chef.
    - An object on the Chef server that contains attributes that describe a node.
    - The more formal name for "node".
- question: Where do you change a cookbook's version?
  answer: 0
  choices:
    - In the metadata.rb file.
    - In the cookbook itself.
    - In the template file.
- question: "True or False: A template enables you to provide placeholders that are replaced with their values when chef-client runs."
  answer: 0
  choices:
    - "True."
    - "False."
