---
:build_date: '2016-07-25'
:machines:
- name: Node
  os: CentOS 7.2
  virtualization: VMWare Fusion
  products:
    chefdk:
      display: Chef Development Kit
      channel: stable
      version: 0.11.2
