---
driver:
  name: ec2
  aws_ssh_key_id: learn-chef
  region: us-east-1
  availability_zone: b
  subnet_id: subnet-3f22bd15
  instance_type: t2.micro
  image_id: ami-49c9295f
  security_group_ids: sg-0e08cf75
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /root/.ssh/learn-chef.pem

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[learn_chef_apache2::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
