---
- question: "Users send requests to a web application with:"
  answer: 1
  choices:
    - A load balancer.
    - A web browser.
    - An application server.

- question: "Users receive responses from:"
  answer: 0
  choices:
    - The application server.
    - The load balancer.
    - The job server.

- question: "Chef enables you to:"
  answer: 2
  choices:
    - Increase the amound of traffic the application server can handle.
    - Send requests to the appropriate application server.
    - Define roles and apply them to the appropriate systems.
