---
- question: "You can define a web application by:"
  answer: 1
  choices:
    - Installing all the necessary software.
    - Using roles to define each of its systems.
    - Drawing a flow chart.
- question: "Written procedures require:"
  answer: 0
  choices:
    - Manual steps.
    - Version control.
    - A good text editor.
- question: "The Chef language:"
  answer: 1
  choices:
    - Is machine readable.
    - Can determine when a system is already in the desired state.
    - Is stored as a PDF.
