---
driver:
  name: azurerm

driver_config:
  subscription_id: 12345678-YOUR-GUID-HERE-123456789ABC
  location: "East US"
  machine_size: "Standard_D2"

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: windows-2012r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
      username: chefuser

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
