---
- question: What is your quest?
  answer: 0
  choices:
    - To learn how to manage a node
    - To seek the grail
- question: What is your favorite color?
  answer: 0
  choices:
    - Blue
    - Red
    - Yellow
- question: What is the airspeed velocity of an unladen swallow?
  answer: 0
  choices:
    - Wait, African or European?
