---
- question: What is a _resource_?
  answer: 1
  choices:
    - Read-only data identified by a type and a name.
    - A description of some piece of a system and its desired state.
    - An ordered series of configuration states.
- question: What is a _recipe_?
  answer: 0
  choices:
    - A file that groups related resources.
    - A file that configures the chef-client run.
    - A file that configures your workstation.
- question: What happens when you don't specify a resource's action?
  answer: 2
  choices:
    - You get an error message but the chef-client run continues.
    - You get an error message and the chef-client run halts.
    - The default action is assumed.
