---
- question: What does the code `package 'httpd'` mean?
  answer: 0
  choices:
    - It identifies a `package` resource.
    - It tags the system as a web server.
    - It is incomplete and will cause an error message.
- question: What determines when Chef applies resources?
  answer: 2
  choices:
    - The order of their precedence.
    - The order of their attributes.
    - The order they're listed in a recipe.
- question: When must you list a resources attributes?
  answer: 2
  choices:
    - Immediately after the resource name.
    - Immediately after the actions.
    - You can list them anywhere within the resource block.
