---
- question: "Chef Automate uses Chef for:"
  answer: 0
  choices:
    - Infrastructure automation.
    - Application automation.
    - Compliance automation.
- question: "Chef Automate uses Habitat for:"
  answer: 1
  choices:
    - Infrastructure automation.
    - Application automation.
    - Compliance automation.
- question: "Chef Automate uses InSpec for:"
  answer: 2
  choices:
    - Infrastructure automation.
    - Application automation.
    - Compliance automation.
- question: "The Chef Automate workflow:"
  answer: 1
  choices:
    - Helps organize tasks needed to complete a project.
    - Enables the continuous delivery of code.
    - Builds test environments for code.
- question: "Chef Automate visibility:"
  answer: 0
  choices:
    - Provides real-time data collection and analysis.
    - Is graphical user interface for configuring Chef Automate.
    - Is a graphical user interface for configuring nodes.
- question: "Chef Automate compliance:"
  answer: 2
  choices:
    - Tests that multiple Chef servers are configured correctly.
    - Tests that Chef Automate is configured correctly.
    - Makes compliance a part of the software deployment pipeline.
- question: "Chef Automate delivers software:"
  answer: 2
  choices:
    - To the cloud.
    - To IaaS environments.
    - To any environment an organization has.
- question: "Organizations can use Chef Automate to:"
  answer: 2
  choices:
    - Provide system administrators with a pipeline for configuring infrastructure.
    - Give developers a way to control the infrastructure.
    - Provide a common way to deploy software across teams and business units.
