---
driver:
  name: ec2
  aws_ssh_key_id: learn-chef
  region: us-east-1
  availability_zone: b
  subnet_id: subnet-3f22bd15
  instance_type: m1.small
  image_id: ami-abf616bd
  security_group_ids: sg-48984132
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /root/.ssh/learn-chef.pem

platforms:
  - name: windows-2012r2

suites:
  - name: default
    run_list:
      - recipe[learn_chef_iis::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
