---
- question: "How do you load a cookbook?"
  answer: 0
  choices:
    - Add a 'depends' statement to the metadata.rb file.
    - Add the cookbook name to the metadata.rb file.
    - Add a cookbook resource to the default.rb recipe.
- question: "Data bags store information as:"
  answer: 1
  choices:
    - Encrypted text.
    - Key-value pairs.
    - A hash table.
- question: "What is 'data_bag_item'?"
  answer: 1
  choices:
    - A method that defines the data bag ID.
    - A helper method.
    - A method that adds a data bag to the correct directory.
- question: "What is 'mysql_client'?"
  answer: 0
  choices:
    - A resource that installs the software that connects to the MySQL server.
    - A resource that configures the MySQL server.
    - A recipe that configures the MySQL server.
- question: "What does the InSpec resource 'mysql_conf' do?"
  answer: 2
  choices:
    - It confirms that the MySQL client is working correctly.
    - It confirms that the MySQL service is working correctly.
    - It tests the contents of the MySQL configuration file.
