---
- question: "What does the `notifies` attribute do?"
  answer: 2
  choices:
    - It alerts the Chef server when the chef-client run fails.
    - It performs a `:restart` action whenever a service fails.
    - It performs a `:restart` action when the package resource performs the `:install` action.
- question: "Which command performs a complete Test Kitchen run, including running InSpec tests?"
  answer: 2
  choices:
    - '`kitchen converge`'
    - '`kitchen start`'
    - '`kitchen test`'
