---
- question: "Which command retrieves version information from Chef Supermarket?"
  answer: 2
  choices:
    - '`chef supermarket show`'
    - '`knife supermarket version`'
    - '`knife supermarket show`'
- question: "What does `default` mean at the beginning of a custom attribute?"
  answer: 1
  choices:
    - It specifies that the custom attribute should be collected by Ohai.
    - It means the attribute is reset at the start of every chef-client run.
    - It means that the custom attribute should be treated like an automatic attribute.
- question: "What does the `default['lamp']['web']['document_root']` attribute do?"
  answer: 1
  choices:
    - It creates a directory.
    - It names a directory and defines where it should be located.
    - It specifies that the directory location should be collected by Ohai.
- question: "What do the InSpec tests do?"
  answer: 0
  choices:
    - They automatically verify the web configuration.
    - They automatically verify that the recipe has no syntactic errors.
    - They automatically verify that the cookbook has no syntactic errors.
